import type { FactorsRoute, FactorsRouteId } from "./factorsMissionTypes";
export const FACTORS_MISSION_ROUTES:readonly FactorsRoute[]=[
{id:"factor-trail",lesson:"LESSON 1",title:"Identifying Factors",shortTitle:"Factor Trail",subtitle:"Trace every factor pair",description:"Follow number gems through factor pairs, checks, and riddles.",accent:"#FF6B4A",accentSoft:"#FFE0D7",icon:"×",reward:{name:"Factor Gem",color:"#FF6B4A"},questionCount:30},
{id:"prime-pulse",lesson:"LESSON 2",title:"Prime & Composite",shortTitle:"Prime Pulse",subtitle:"Scan the number field",description:"Spot prime numbers, composites, and the special role of one.",accent:"#7B61FF",accentSoft:"#E9E4FF",icon:"◈",reward:{name:"Prime Spark",color:"#7B61FF"},questionCount:30},
{id:"gcf-guild",lesson:"LESSONS 3–4",title:"Greatest Common Factor",shortTitle:"G.C.F. Guild",subtitle:"Join the strongest match",description:"Find common factors and build equal groups with the greatest match.",accent:"#2EC4B6",accentSoft:"#D7FBF6",icon:"⇄",reward:{name:"G.C.F. Crest",color:"#2EC4B6"},questionCount:30},
{id:"multiple-momentum",lesson:"LESSON 4",title:"Multiples",shortTitle:"Multiple Momentum",subtitle:"Ride the skip-count lane",description:"Launch along patterns, missing multiples, and number-line routes.",accent:"#FFB703",accentSoft:"#FFF1C4",icon:"→",reward:{name:"Multiple Bolt",color:"#FFB703"},questionCount:30},
{id:"common-crossing",lesson:"LESSON 5",title:"Common Multiples",shortTitle:"Common Crossing",subtitle:"Meet on the same square",description:"Cross two number lanes where their multiples meet.",accent:"#3F8EFC",accentSoft:"#DFEDFF",icon:"⌁",reward:{name:"Crossing Orb",color:"#3F8EFC"},questionCount:30},
{id:"relationship-relay",lesson:"LESSON 6",title:"Factors & Multiples",shortTitle:"Relationship Relay",subtitle:"Connect every product",description:"Race through factor and multiple relationships, clues, and challenges.",accent:"#F05D9E",accentSoft:"#FFE0EF",icon:"↔",reward:{name:"Connection Star",color:"#F05D9E"},questionCount:30},
{id:"factors-master-exam",lesson:"MASTER EXAM",title:"Factors & Multiples Master",shortTitle:"Master Exam",subtitle:"Play the complete unit",description:"A mixed final arena using only the supplied Unit Six Assessment.",accent:"#FFB703",accentSoft:"#FFF1C4",icon:"★",reward:{name:"Factor Crown",color:"#FFB703"},questionCount:15,isMaster:true}
] as const;
export const getFactorsMissionRoute=(id:FactorsRouteId)=>{const route=FACTORS_MISSION_ROUTES.find((item)=>item.id===id);if(!route)throw new Error(`Unknown Unit 6 route: ${id}`);return route;};
