export type Unit6GcfQuestion = {
  id: string;
  lesson: "greatest-common-factor";
  skill: "definition" | "common-factors" | "greatest-common-factor" | "grouping" | "multiple-choice" | "challenge";
  prompt: string;
  expectedAnswer: string;
  explanation: string;
  sourceLabels: readonly string[];
  choices?: readonly string[];
};

export const UNIT6_GCF_LESSON_NOTES = [
  "Common factors of two numbers are factors that are the same.",
  "The greatest common factor (G.C.F.) is the greatest number that is a factor of both numbers.",
  "To find a G.C.F., list the factors of each number, identify common factors, then choose the greatest common factor.",
  "1 is the common factor of all whole numbers; all prime-number pairs share the common factor 1.",
] as const;

export const UNIT6_GREATEST_COMMON_FACTOR_QUESTIONS: readonly Unit6GcfQuestion[] = [
  { id: "u6-l3-gcf-definition", lesson: "greatest-common-factor", skill: "definition", prompt: "Complete: The G.C.F. of two numbers is the greatest number that is a factor of ___.", expectedAnswer: "both", explanation: "The G.C.F. must be a factor of each number in the pair.", sourceLabels: [] },
  { id: "u6-l3-gcf-18-24", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 18 and 24.", expectedAnswer: "1, 2, 3, 6; G.C.F. 6", explanation: "The common factors are 1, 2, 3, and 6; 6 is the greatest.", sourceLabels: [] },
  { id: "u6-l3-gcf-12-15", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 12 and 15.", expectedAnswer: "1, 3; G.C.F. 3", explanation: "The shared factors are 1 and 3.", sourceLabels: [] },
  { id: "u6-l3-gcf-16-28", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 16 and 28.", expectedAnswer: "1, 2, 4; G.C.F. 4", explanation: "The common factors are 1, 2, and 4.", sourceLabels: [] },
  { id: "u6-l3-gcf-7-11", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 7 and 11.", expectedAnswer: "1; G.C.F. 1", explanation: "7 and 11 are prime, so their only common factor is 1.", sourceLabels: [] },
  { id: "u6-l3-grouping-fruit-yogurt", lesson: "greatest-common-factor", skill: "grouping", prompt: "Adam has 28 pieces of fruit and 14 yogurt cups. He wants identical servings with nothing left. What is the greatest number of servings, and how many fruit pieces and yogurt cups are in each serving?", expectedAnswer: "14 servings; 2 fruit pieces and 1 yogurt cup each", explanation: "G.C.F.(28, 14) = 14; 28 ÷ 14 = 2 and 14 ÷ 14 = 1.", sourceLabels: [] },
  { id: "u6-l3-common-9-12", lesson: "greatest-common-factor", skill: "common-factors", prompt: "List the common factors of 9 and 12.", expectedAnswer: "1, 3", explanation: "The factors shared by 9 and 12 are 1 and 3.", sourceLabels: [] },
  { id: "u6-l3-common-25-15", lesson: "greatest-common-factor", skill: "common-factors", prompt: "List the common factors of 25 and 15.", expectedAnswer: "1, 5", explanation: "Both 25 and 15 are divisible by 1 and 5.", sourceLabels: [] },
  { id: "u6-l3-common-4-12", lesson: "greatest-common-factor", skill: "common-factors", prompt: "List the common factors of 4 and 12.", expectedAnswer: "1, 2, 4", explanation: "Each of 1, 2, and 4 divides both numbers.", sourceLabels: [] },
  { id: "u6-l3-common-10-35", lesson: "greatest-common-factor", skill: "common-factors", prompt: "List the common factors of 10 and 35.", expectedAnswer: "1, 5", explanation: "The shared factors are 1 and 5.", sourceLabels: [] },
  { id: "u6-l3-common-17-34", lesson: "greatest-common-factor", skill: "common-factors", prompt: "List the common factors of 17 and 34.", expectedAnswer: "1, 17", explanation: "34 is 2 × 17, so 17 is a shared factor.", sourceLabels: [] },
  { id: "u6-l3-common-18-24", lesson: "greatest-common-factor", skill: "common-factors", prompt: "List the common factors of 18 and 24.", expectedAnswer: "1, 2, 3, 6", explanation: "These four numbers divide both 18 and 24.", sourceLabels: [] },
  { id: "u6-l3-common-25-30", lesson: "greatest-common-factor", skill: "common-factors", prompt: "List the common factors of 25 and 30.", expectedAnswer: "1, 5", explanation: "Both numbers are divisible by 1 and 5.", sourceLabels: [] },
  { id: "u6-l3-common-22-44", lesson: "greatest-common-factor", skill: "common-factors", prompt: "List the common factors of 22 and 44.", expectedAnswer: "1, 2, 11, 22", explanation: "22 is a factor of 44, so every factor of 22 is shared.", sourceLabels: [] },
  { id: "u6-l3-gcf-4-6", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 4 and 6.", expectedAnswer: "1, 2; G.C.F. 2", explanation: "The shared factors are 1 and 2.", sourceLabels: [] },
  { id: "u6-l3-gcf-10-30", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 10 and 30.", expectedAnswer: "1, 2, 5, 10; G.C.F. 10", explanation: "10 is the greatest factor shared by 10 and 30.", sourceLabels: [] },
  { id: "u6-l3-gcf-12-18", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 12 and 18.", expectedAnswer: "1, 2, 3, 6; G.C.F. 6", explanation: "6 is the greatest shared factor.", sourceLabels: ["Sharkia 22"] },
  { id: "u6-l3-gcf-6-12", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 6 and 12.", expectedAnswer: "1, 2, 3, 6; G.C.F. 6", explanation: "Every factor of 6 is also a factor of 12.", sourceLabels: ["Giza – Abo El-Nomros 23"] },
  { id: "u6-l3-gcf-10-15", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the common factors and G.C.F. of 10 and 15.", expectedAnswer: "1, 5; G.C.F. 5", explanation: "The greatest shared factor is 5.", sourceLabels: ["Souhag 23"] },
  { id: "u6-l3-gcf-30-45", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 30 and 45.", expectedAnswer: "15", explanation: "15 is the greatest number that divides both 30 and 45.", sourceLabels: ["Ismailia 22"] },
  { id: "u6-l3-gcf-12-18-labels", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 12 and 18.", expectedAnswer: "6", explanation: "6 divides both 12 and 18.", sourceLabels: ["Giza 23", "Cairo 23"] },
  { id: "u6-l3-gcf-40-50", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 40 and 50.", expectedAnswer: "10", explanation: "10 is the greatest common factor.", sourceLabels: [] },
  { id: "u6-l3-gcf-10-45", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 10 and 45.", expectedAnswer: "5", explanation: "5 is the greatest shared factor.", sourceLabels: [] },
  { id: "u6-l3-gcf-10-24", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 10 and 24.", expectedAnswer: "2", explanation: "2 is the greatest shared factor.", sourceLabels: [] },
  { id: "u6-l3-gcf-35-25", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 35 and 25.", expectedAnswer: "5", explanation: "5 is the greatest shared factor.", sourceLabels: ["Monofia – Sers El Layan 23", "Monofia – Shebin El-Kom 22"] },
  { id: "u6-l3-gcf-40-48", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 40 and 48.", expectedAnswer: "8", explanation: "8 is the greatest common factor.", sourceLabels: [] },
  { id: "u6-l3-gcf-33-11", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 33 and 11.", expectedAnswer: "11", explanation: "11 divides both 33 and 11.", sourceLabels: [] },
  { id: "u6-l3-gcf-20-12", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 20 and 12.", expectedAnswer: "4", explanation: "4 is the greatest factor shared by 20 and 12.", sourceLabels: ["Cairo 23"] },
  { id: "u6-l3-gcf-18-30", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 18 and 30.", expectedAnswer: "6", explanation: "6 is the greatest factor shared by 18 and 30.", sourceLabels: ["Cairo – El-Marg 23"] },
  { id: "u6-l3-gcf-24-18", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 24 and 18.", expectedAnswer: "6", explanation: "6 is the greatest shared factor.", sourceLabels: ["Giza 23"] },
  { id: "u6-l3-gcf-12-15-label", lesson: "greatest-common-factor", skill: "greatest-common-factor", prompt: "Find the G.C.F. of 12 and 15.", expectedAnswer: "3", explanation: "3 is the greatest shared factor.", sourceLabels: ["Giza 23"] },
  { id: "u6-l3-grouping-pencils-erasers", lesson: "greatest-common-factor", skill: "grouping", prompt: "Sylvia has 21 pencils and 14 erasers. She wants identical groups. What is the greatest number of groups, and how many pencils and erasers are in each group?", expectedAnswer: "7 groups; 3 pencils and 2 erasers each", explanation: "G.C.F.(21, 14) = 7; 21 ÷ 7 = 3 and 14 ÷ 7 = 2.", sourceLabels: [] },
  { id: "u6-l3-grouping-girls-boys", lesson: "greatest-common-factor", skill: "grouping", prompt: "There are 40 girls and 32 boys who want to participate in lap-on teams. What is the greatest number of identical teams, and how many girls and boys are in each team?", expectedAnswer: "8 teams; 5 girls and 4 boys each", explanation: "G.C.F.(40, 32) = 8.", sourceLabels: [] },
  { id: "u6-l3-grouping-field-trip", lesson: "greatest-common-factor", skill: "grouping", prompt: "A class has 36 girls and 27 boys. Students will be divided into equal groups with the same number of girls and boys. What is the greatest number of groups, and how many girls and boys are in each group?", expectedAnswer: "9 groups; 4 girls and 3 boys each", explanation: "G.C.F.(36, 27) = 9.", sourceLabels: [] },
  { id: "u6-l3-grouping-flowers", lesson: "greatest-common-factor", skill: "grouping", prompt: "Mohab has 7 roses and 14 daisies. He wants identical flower arrangements with nothing left. What is the greatest number of arrangements, and how many roses and daisies are in each arrangement?", expectedAnswer: "7 arrangements; 1 rose and 2 daisies each", explanation: "G.C.F.(7, 14) = 7.", sourceLabels: [] },
  { id: "u6-l3-grouping-marbles", lesson: "greatest-common-factor", skill: "grouping", prompt: "Eslam has 60 blue marbles and 24 red marbles. He wants identical groups with nothing left. What is the greatest number of groups, and how many blue and red marbles are in each group?", expectedAnswer: "12 groups; 5 blue marbles and 2 red marbles each", explanation: "G.C.F.(60, 24) = 12.", sourceLabels: [] },
  { id: "u6-l3-grouping-snack-packs", lesson: "greatest-common-factor", skill: "grouping", prompt: "Amira has 24 apples and 36 small bags of candy. She wants identical snack packs with nothing left. What is the greatest number of snack packs, and how many apples and candy bags are in each pack?", expectedAnswer: "12 snack packs; 2 apples and 3 candy bags each", explanation: "G.C.F.(24, 36) = 12.", sourceLabels: [] },
  { id: "u6-l3-challenge-15-18-21", lesson: "greatest-common-factor", skill: "challenge", prompt: "Find the G.C.F. of 15, 18, and 21.", expectedAnswer: "3", explanation: "3 is a factor of all three numbers and no greater common factor is shared.", sourceLabels: [] },
  { id: "u6-l3-mcq-common-all", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "The common factor of all numbers is ___.", expectedAnswer: "1", explanation: "1 is a factor of every whole number.", sourceLabels: ["Kalyoubia 23", "Beheira 23"], choices: ["3", "2", "1", "0"] },
  { id: "u6-l3-mcq-common-4-6", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "Which are the common factors of 4 and 6?", expectedAnswer: "1 and 2", explanation: "1 and 2 divide both 4 and 6.", sourceLabels: [], choices: ["1 and 2", "1 and 3", "2 and 3", "3 and 4"] },
  { id: "u6-l3-mcq-common-15-25", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "Which are the common factors of 15 and 25?", expectedAnswer: "1 and 5", explanation: "Both 15 and 25 have factors 1 and 5.", sourceLabels: [], choices: ["1 and 3", "1 and 5", "1 and 15", "1 and 25"] },
  { id: "u6-l3-mcq-gcf-12-6", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "Which number is the greatest common factor (G.C.F.) of 12 and 6?", expectedAnswer: "6", explanation: "6 is the largest number that divides both 12 and 6.", sourceLabels: ["Cairo – Heliopolis 23", "El-Beheira – Kafr El-Dawwar 22"], choices: ["2", "3", "6", "12"] },
  { id: "u6-l3-mcq-gcf-5-11", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "Which number is the greatest common factor (G.C.F.) of 5 and 11?", expectedAnswer: "1", explanation: "5 and 11 share only the factor 1.", sourceLabels: [], choices: ["2", "5", "1", "11"] },
  { id: "u6-l3-mcq-gcf-45-60", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "Which number is the greatest common factor of 45 and 60?", expectedAnswer: "15", explanation: "15 is the greatest shared factor.", sourceLabels: ["Damietta 22"], choices: ["5", "20", "15", "30"] },
  { id: "u6-l3-mcq-gcf-10-24", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "The greatest common factor (G.C.F.) of 10 and 24 is ___.", expectedAnswer: "2", explanation: "2 is the greatest number that divides both 10 and 24.", sourceLabels: ["Aswan 23"], choices: ["34", "22", "2", "14"] },
  { id: "u6-l3-mcq-gcf-20-30", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "The G.C.F. of 20 and 30 is ___.", expectedAnswer: "10", explanation: "10 is the greatest common factor.", sourceLabels: [], choices: ["1", "4", "5", "10"] },
  { id: "u6-l3-mcq-common-7-14", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "1 and 7 are the common factors of ___.", expectedAnswer: "7 and 14", explanation: "Both 7 and 14 are divisible by 1 and 7.", sourceLabels: [], choices: ["2 and 7", "2 and 14", "7 and 12", "7 and 14"] },
  { id: "u6-l3-mcq-factor-48-54", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "Which number is a common factor of 48 and 54?", expectedAnswer: "6", explanation: "6 divides both 48 and 54.", sourceLabels: [], choices: ["2", "6", "8", "9"] },
  { id: "u6-l3-mcq-same-gcf", lesson: "greatest-common-factor", skill: "multiple-choice", prompt: "Which pair of numbers has the same greatest common factor as 42 and 12?", expectedAnswer: "18 and 30", explanation: "G.C.F.(42, 12) = 6 and G.C.F.(18, 30) = 6.", sourceLabels: [], choices: ["9 and 6", "8 and 24", "16 and 60", "18 and 30"] },
] as const;
