import { useState } from "react";
import { ArrowLeft, ChevronRight, LockKeyhole, Music2, Play, Sparkles, Star, VolumeX } from "lucide-react";
import AreaMissionWorld from "@/components/AreaMissionWorld";
import { AREA_MISSION_ROUTES } from "@/game/areaMissionCurriculum";
import { isAreaExplorerMissionUnlocked, readAreaMissionProgress } from "@/game/areaMissionProgress";
import type { AreaMissionProgressState, AreaRouteId } from "@/game/areaMissionTypes";
import "./areaMission.css";

const iconFor = (routeId: AreaRouteId) => routeId === "perimeter" ? "⌁" : routeId === "area" ? "▦" : routeId === "unknown-dimensions" ? "⌖" : routeId === "complex-shapes" ? "⌞" : "✦";

export default function AreaMissionChapter({ onExit, musicOn, onToggleMusic }: { onExit: () => void; musicOn: boolean; onToggleMusic: () => void }) {
  const [activeRoute, setActiveRoute] = useState<AreaRouteId | null>(() => { if (typeof window === "undefined") return null; const requested = new URLSearchParams(window.location.search).get("area-route") as AreaRouteId | null; return requested && AREA_MISSION_ROUTES.some((route) => route.id === requested) ? requested : null; });
  const [progress, setProgress] = useState<AreaMissionProgressState>(readAreaMissionProgress);
  const lessons = AREA_MISSION_ROUTES.filter((route) => !route.isMaster);
  const unlocked = isAreaExplorerMissionUnlocked(progress);
  if (activeRoute) return <AreaMissionWorld routeId={activeRoute} musicOn={musicOn} onToggleMusic={onToggleMusic} onBack={() => { setProgress(readAreaMissionProgress()); setActiveRoute(null); }} />;
  return <main className="am-chapter" aria-labelledby="area-mission-title"><div className="am-map-orb am-map-orb-a" /><div className="am-map-orb am-map-orb-b" /><header className="am-topbar"><button onClick={onExit}><ArrowLeft size={17} /> MAIN MENU</button><strong><i>✦</i> MISSION EXPLORE AREA <b>MOSY MATH ADVENTURE · UNIT 4</b></strong><button onClick={onToggleMusic} aria-label={musicOn ? "Turn background music off" : "Turn background music on"}>{musicOn ? <Music2 size={18} /> : <VolumeX size={18} />} {musicOn ? "MUSIC" : "MUTED"}</button></header><section className="am-hero"><div className="am-hero-visual" style={{ backgroundImage: "url(manus-storage/mission-explore-area-unit4-visual-target_13331744.png)" }}><i /><b>▦</b><em>⌁</em></div><div><p><Sparkles size={15} /> UNIT 4 EXPLORATION MAP</p><h1 id="area-mission-title">Mission Explore<br /><span>Area – Unit 4</span></h1><h2>Trace every path, tile every space, unlock missing sides, then master the complex garden.</h2><div><b>4 <small>LESSON MISSIONS</small></b><b>{lessons.reduce((total, route) => total + progress[route.id as keyof AreaMissionProgressState].completedLevels.length, 0)} <small>MAP GEMS</small></b><b>1 <small>FINAL EXPEDITION</small></b></div></div></section><section className="am-route-section"><header><div><p>EXPLORE IN ORDER</p><h2>Choose a map mission</h2></div><span>Easy → Normal → Hard</span></header><div className="am-route-grid">{lessons.map((route) => { const routeProgress = progress[route.id as keyof AreaMissionProgressState]; return <article key={route.id} style={{ "--am-accent": route.accent, "--am-soft": route.accentSoft } as React.CSSProperties}><div><span>{route.lesson}</span><i>{iconFor(route.id)}</i></div><div className="am-route-icon"><i>{iconFor(route.id)}</i><b>✦</b></div><p>{route.subtitle}</p><h3>{route.shortTitle}</h3><small>{route.description}</small><em><b>✦</b> {routeProgress.completedLevels.length} / 3 MAP GEMS</em><button onClick={() => setActiveRoute(route.id)}><Play size={15} fill="currentColor" /> PLAY {route.shortTitle.toUpperCase()}<ChevronRight size={16} /></button></article>; })}</div></section><section className={`am-final ${unlocked ? "is-open" : "is-locked"}`}><div className="am-final-orb">✦</div><div><p>{unlocked ? "FINAL EXPEDITION UNLOCKED" : "FINAL EXPEDITION · LOCKED"}</p><h2>Area Explorer Mission</h2><span>Mix every Unit 4 skill: perimeter, area, unknown dimensions, and complex shapes.</span><b>{lessons.filter((route) => progress[route.id as keyof AreaMissionProgressState].completedLevels.includes("hard")).length} / 4 ROUTES MASTERED</b></div><button disabled={!unlocked} onClick={() => setActiveRoute("area-explorer-mission")}>{unlocked ? <><Star size={17} fill="currentColor" /> START FINAL MISSION</> : <><LockKeyhole size={16} /> MASTER THE 4 ROUTES</>}</button></section></main>;
}
