import { useMemo, useState } from "react";
import { ArrowLeft, ChevronRight, Heart, Music2, Play, VolumeX } from "lucide-react";
import { getMd1Route } from "@/game/mdPart1Curriculum";
import { getMd1Questions } from "@/game/mdPart1Questions";
import { readMd1, recordMd1 } from "@/game/mdPart1Progress";
import type { Md1LessonRouteId, Md1Level, Md1RouteId } from "@/game/mdPart1Types";
import { roundRushSound } from "@/game/sound";
import "./areaMission.css";

const canonical = (value: string) => value.replace(/\s/g, "").replace(/,/g, "").toLowerCase();
const correctMotivations = ["perfect", "wellDone", "onARoll", "brilliant"] as const;
const wrongMotivations = ["keepGoing", "youWereClose", "tryAgain", "almostThere"] as const;
const shuffle = <T,>(items: readonly T[]) => {
  const result = [...items];
  for (let index = result.length - 1; index > 0; index -= 1) {
    const next = Math.floor(Math.random() * (index + 1));
    [result[index], result[next]] = [result[next]!, result[index]!];
  }
  return result;
};
export default function MdPart1World({ routeId, onBack, musicOn, onToggleMusic }: { routeId: Md1RouteId; onBack: () => void; musicOn: boolean; onToggleMusic: () => void }) {
  const route = getMd1Route(routeId); const master = !!route.isMaster;
  const [level, setLevel] = useState<Md1Level>("easy"); const [started, setStarted] = useState(false); const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [hearts, setHearts] = useState(5); const [chosen, setChosen] = useState<string | null>(null); const [run, setRun] = useState(0);
  const questions = useMemo(() => shuffle(getMd1Questions(routeId, master ? undefined : level)), [routeId, level, master, run]); const question = questions[index]; const orderedChoices = useMemo(() => question ? shuffle(question.choices) : [], [question?.id, run]); const done = index >= questions.length || hearts === 0;
  const choose = (choice: string) => { if (!question || chosen || done) return; const correct = canonical(choice) === canonical(question.correctChoice); setChosen(choice); if (correct) { setScore((value) => value + 100); roundRushSound.correct(); roundRushSound.motivate(correctMotivations[Math.floor(Math.random() * correctMotivations.length)]!); } else { setHearts((value) => value - 1); roundRushSound.incorrect(); roundRushSound.motivateWrong(wrongMotivations[Math.floor(Math.random() * wrongMotivations.length)]!); } window.setTimeout(() => { if (!master && correct && index === questions.length - 1) recordMd1(readMd1(), routeId as Md1LessonRouteId, level); setChosen(null); setIndex((value) => value + 1); }, 1200); };
  const style = { "--am-accent": route.accent, "--am-soft": route.soft } as React.CSSProperties;
  if (!started) return <main className="am-world fm-world" style={style}><header className="am-topbar"><button onClick={onBack}><ArrowLeft size={17} /> MISSION MAP</button><strong><i>{route.icon}</i>{route.lesson}<b>{route.title}</b></strong><button onClick={onToggleMusic}>{musicOn ? <Music2 size={18} /> : <VolumeX size={18} />} MUSIC</button></header><section className="am-intro"><div className="am-route-emblem"><i>{route.icon}</i></div><div><p>✦ {route.subtitle.toUpperCase()}</p><h1>{route.title}</h1><h2>{route.description}</h2>{master ? <div className="am-master-note">✦ 15 verified questions from Lessons 1–6 only.</div> : <div className="am-levels">{(["easy", "normal", "hard"] as Md1Level[]).map((item) => <button key={item} className={level === item ? "is-active" : ""} onClick={() => setLevel(item)}><i>{item[0]!.toUpperCase()}</i><span><b>{item[0]!.toUpperCase() + item.slice(1)}</b><small>10 questions</small></span></button>)}</div>}<button className="am-primary" onClick={() => { roundRushSound.unlock(); setStarted(true); }}><Play size={18} fill="currentColor" /> START MISSION <ChevronRight size={17} /></button></div></section></main>;
  if (done) return <main className="am-world fm-world" style={style}><section className="am-result"><div className="am-result-medal">★</div><p>MISSION COMPLETE</p><h1>{route.shortTitle} complete!</h1><span>Score: {score} · Questions cleared: {Math.min(index, questions.length)} / {questions.length}</span><button className="am-primary" onClick={() => { setIndex(0); setScore(0); setHearts(5); setRun((value) => value + 1); setStarted(false); }}>PLAY AGAIN</button><button className="am-secondary" onClick={onBack}>MISSION MAP</button></section></main>;
  return <main className="am-world am-playing fm-world" style={style}><header className="am-hud"><button onClick={onBack}><ArrowLeft size={17} /> MAP</button><strong><i>{route.icon}</i><span>{route.lesson}<b>{route.shortTitle}</b></span></strong><div className="am-progress"><span>{index + 1} / {questions.length}</span><i><b style={{ width: `${(index / questions.length) * 100}%` }} /></i></div><div className="am-stats"><b>✦ {score}</b><span>{Array.from({ length: 5 }, (_, number) => <Heart key={number} size={17} fill={number < hearts ? "currentColor" : "transparent"} />)}</span></div></header><section className="am-playfield"><aside><span>PART 1</span><b>×{Math.max(1, Math.floor(score / 300) + 1)}</b><i>★</i></aside><div className="am-shape-board fm-factor-board" aria-hidden="true"><i>×</i><i>÷</i><i>10</i><i>R</i><b>+</b></div><article className="am-question"><p>{question!.skill.toUpperCase()}</p>{question!.sourceLabels.length ? <div className="am-source-labels">{question!.sourceLabels.map((source) => <b key={source}>[{source}]</b>)}</div> : null}<h1>{question!.prompt}</h1></article><div className="am-answer-grid">{orderedChoices.map((choice, number) => { const correct = canonical(choice) === canonical(question!.correctChoice); return <button key={`${question!.id}-${choice}`} disabled={!!chosen} className={chosen ? correct ? "is-correct" : chosen === choice ? "is-wrong" : "" : ""} onClick={() => choose(choice)}><i>{number + 1}</i><b>{choice}</b></button>; })}</div>{chosen ? <div className="am-feedback" role="status"><div><b>{canonical(chosen) === canonical(question!.correctChoice) ? "Brilliant!" : "Keep going!"}</b><p>{question!.explanation}</p></div></div> : null}</section></main>;
}
