import { useEffect, useMemo, useRef, useState } from "react";
import { ArrowLeft, Check, ChevronRight, Heart, Lightbulb, LockKeyhole, Music2, Play, RotateCcw, Sparkles, Volume2, VolumeX } from "lucide-react";
import { MULTIPLICATION_LEVELS, type MultiplicationLessonRouteId, type MultiplicationLevelId, type MultiplicationRouteId } from "@/game/multiplicationMissionTypes";
import { getMultiplicationMissionRoute } from "@/game/multiplicationMissionCurriculum";
import { getMultiplicationMissionQuestions } from "@/game/multiplicationMissionQuestions";
import { createPresentationSeed, shuffledChoices, shuffledQuestions } from "@/game/answerFairness";
import { isMultiplicationLevelUnlocked, readMultiplicationMissionProgress, recordMultiplicationMissionResult } from "@/game/multiplicationMissionProgress";
import { selectMotivation, selectWrongMotivation, type Motivation, type WrongMotivation } from "@/game/motivation";
import { roundRushSound } from "@/game/sound";
import { awardPlayerScore } from "@/game/playerProfile";
import "./areaMission.css";

type Phase = "intro" | "playing" | "feedback" | "result";
const canonical = (value: string) => value.normalize("NFC").replace(/\s+/g, " ").trim().toLowerCase();

export default function MultiplicationMissionWorld({ routeId, onBack, musicOn, onToggleMusic }: { routeId: MultiplicationRouteId; onBack: () => void; musicOn: boolean; onToggleMusic: () => void }) {
  const route = getMultiplicationMissionRoute(routeId); const isMaster = Boolean(route.isMaster); const lessonId = isMaster ? null : routeId as MultiplicationLessonRouteId;
  const [progress, setProgress] = useState(readMultiplicationMissionProgress); const [level, setLevel] = useState<MultiplicationLevelId>("easy"); const [runSeed, setRunSeed] = useState(createPresentationSeed); const [phase, setPhase] = useState<Phase>("intro");
  const questions = useMemo(() => shuffledQuestions(getMultiplicationMissionQuestions(routeId, isMaster ? undefined : level), runSeed).map((question) => ({ ...question, choices: shuffledChoices(question.id, question.choices, runSeed) })), [routeId, isMaster, level, runSeed]); const [index, setIndex] = useState(0); const [hearts, setHearts] = useState(5); const [score, setScore] = useState(0); const [combo, setCombo] = useState(0); const [bestCombo, setBestCombo] = useState(0); const [selected, setSelected] = useState<string | null>(null); const [soundOn, setSoundOn] = useState(true); const [feedback, setFeedback] = useState(""); const [lastCorrect, setLastCorrect] = useState<Motivation | null>(null); const [lastWrong, setLastWrong] = useState<WrongMotivation | null>(null); const saved = useRef(false);
  const question = questions[Math.min(index, questions.length - 1)]!; const selectedLevel = MULTIPLICATION_LEVELS.find((item) => item.id === level) ?? MULTIPLICATION_LEVELS[0]!;
  const restart = (next = level) => { roundRushSound.unlock(); roundRushSound.enableHoverCues(); roundRushSound.launch(); if (musicOn) void document.querySelector("audio")?.play().catch(() => undefined); setLevel(next); setRunSeed(createPresentationSeed()); setIndex(0); setHearts(5); setScore(0); setCombo(0); setBestCombo(0); setSelected(null); setFeedback(""); saved.current = false; setPhase("playing"); };
  const finish = (completed: boolean) => { if (lessonId && !saved.current) { setProgress(recordMultiplicationMissionResult(progress, lessonId, level, score, completed)); saved.current = true; } if (completed) roundRushSound.victory(); setPhase("result"); };
  const advance = () => { if (hearts <= 0 || index >= questions.length - 1) finish(hearts > 0); else { setIndex((n) => n + 1); setSelected(null); setFeedback(""); setPhase("playing"); } };
  const answer = (choice: string) => { if (phase !== "playing") return; roundRushSound.unlock(); setSelected(choice); if (canonical(choice) === canonical(question.correctChoice)) { const nextCombo = combo + 1; const note = selectMotivation({ questionNumber: index + 1, combo: nextCombo, last: lastCorrect }); const points = Math.round((100 + combo * 25) * (isMaster ? 1.5 : selectedLevel.multiplier)); setLastCorrect(note); setFeedback(`${note.text} +${points} points. ${question.explanation}`); setScore((n) => n + points); awardPlayerScore(points, "multiplication-mission"); setCombo(nextCombo); setBestCombo((n) => Math.max(n, nextCombo)); roundRushSound.correct(0); if (soundOn) window.setTimeout(() => roundRushSound.motivate(note.clip), 250); } else { const note = selectWrongMotivation(index + 1, lastWrong); setLastWrong(note); setFeedback(`${note.text} ${question.explanation}`); setHearts((n) => Math.max(0, n - 1)); setCombo(0); roundRushSound.incorrect(); if (soundOn) window.setTimeout(() => roundRushSound.motivateWrong(note.clip), 160); } setPhase("feedback"); };
  useEffect(() => { if (phase !== "feedback") return; const t = window.setTimeout(advance, canonical(selected ?? "") === canonical(question.correctChoice) ? 1750 : 2600); return () => window.clearTimeout(t); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, selected, question.id]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { const option = Number(event.key) - 1; if (phase === "playing" && option >= 0 && option < 4) answer(question.choices[option]!); }; window.addEventListener("keydown", handler); return () => window.removeEventListener("keydown", handler); // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [phase, question.id]);
  const completed = hearts > 0 && index >= questions.length - 1; const style = { "--am-accent": route.accent, "--am-soft": route.accentSoft } as React.CSSProperties;
  if (phase === "intro") return <main className="am-world mm-world" style={style}><header className="am-topbar"><button onClick={onBack}><ArrowLeft size={17} /> MISSION MAP</button><strong><i>{route.icon}</i>{route.lesson}<b>{route.title}</b></strong><button onClick={onToggleMusic}>{musicOn ? <Music2 size={18} /> : <VolumeX size={18} />} {musicOn ? "MUSIC" : "MUTED"}</button></header><section className="am-intro"><div className="am-route-emblem"><i>{route.icon}</i><span /><span /></div><div><p><Sparkles size={15} /> {route.subtitle.toUpperCase()}</p><h1>{route.title}</h1><h2>{route.description}</h2>{isMaster ? <div className="am-master-note">✦ 15 mixed Master Unit Exam questions from the teacher assessment.</div> : <div className="am-levels">{MULTIPLICATION_LEVELS.map((item) => { const unlocked = isMultiplicationLevelUnlocked(progress, lessonId!, item.id); return <button disabled={!unlocked} onClick={() => setLevel(item.id)} key={item.id} className={level === item.id ? "is-active" : ""}>{unlocked ? <i>{item.id[0]!.toUpperCase()}</i> : <LockKeyhole size={15} />}<span><b>{item.label}</b><small>{item.hint} · 10 questions</small></span><em>{item.multiplier}×</em></button>; })}</div>}<button className="am-primary" onClick={() => restart()}><Play size={19} fill="currentColor" /> {isMaster ? "START MASTER EXAM" : `START ${selectedLevel.label.toUpperCase()} MISSION`}<ChevronRight size={18} /></button><small className="am-keyboard">Choose a token with your pointer or press <kbd>1</kbd> <kbd>2</kbd> <kbd>3</kbd> <kbd>4</kbd>.</small></div></section></main>;
  if (phase === "result") return <main className="am-world mm-world" style={style}><header className="am-topbar"><button onClick={onBack}><ArrowLeft size={17} /> MISSION MAP</button><strong><i>★</i>{route.lesson}<b>{route.shortTitle}</b></strong><button onClick={onToggleMusic}>{musicOn ? <Music2 size={18} /> : <VolumeX size={18} />} {musicOn ? "MUSIC" : "MUTED"}</button></header><section className="am-result"><div className="am-result-medal">{completed ? "★" : "…"}</div><p>{completed ? "MISSION COMPLETE" : "MISSION PAUSED"}</p><h1>{completed ? `${route.reward.name} won!` : "Your multiplier is waiting."}</h1><span>{completed ? `You cleared ${questions.length} ${isMaster ? "mixed" : selectedLevel.label.toLowerCase()} multiplication questions.` : "Try again when you are ready."}</span><div><b>SCORE<em>{score.toLocaleString()}</em></b><b>BEST COMBO<em>×{Math.max(1, bestCombo)}</em></b><b>HEARTS<em>{hearts} / 5</em></b></div><button className="am-primary" onClick={() => restart()}><RotateCcw size={18} /> PLAY AGAIN</button><button className="am-secondary" onClick={onBack}>CHOOSE A MISSION <ChevronRight size={17} /></button></section></main>;
  return <main className="am-world am-playing mm-world" style={style}><header className="am-hud"><button onClick={onBack}><ArrowLeft size={17} /> MAP</button><strong><i>{route.icon}</i><span>{route.lesson} · {isMaster ? "MASTER EXAM" : `${selectedLevel.label.toUpperCase()} MISSION`}<b>{route.shortTitle}</b></span></strong><div className="am-progress"><span>{index + 1} / {questions.length}</span><i><b style={{ width: `${Math.min(100, (index / questions.length) * 100)}%` }} /></i></div><div className="am-stats"><b>✦ {score}</b><span>{Array.from({ length: 5 }, (_, n) => <Heart key={n} size={17} fill={n < hearts ? "currentColor" : "transparent"} />)}</span><button onClick={() => { const next = !soundOn; setSoundOn(next); roundRushSound.setEnabled(next); }}>{soundOn ? <Volume2 size={17} /> : <VolumeX size={17} />}</button><button onClick={onToggleMusic}><Music2 size={17} /></button></div></header><section className="am-playfield"><aside><span>COMBO</span><b>×{Math.max(1, combo)}</b><i>×</i></aside><div className="am-shape-board mm-math-board" aria-hidden="true"><span className="am-shape-a" /><span className="am-shape-b" /><i>×</i><i>=</i><i>×</i></div><article className="am-question"><p>{question.skill.toUpperCase()}</p>{question.sourceLabels.length ? <div className="am-source-labels">{question.sourceLabels.map((label) => <b key={label}>[{label}]</b>)}</div> : null}<h1>{question.prompt}</h1><span><Lightbulb size={15} /> Build the multiplication clue, then choose the strongest answer token.</span></article><div className={`am-answer-grid ${phase === "feedback" ? "is-resolving" : ""}`}>{question.choices.map((choice, choiceIndex) => { const correct = canonical(choice) === canonical(question.correctChoice); const state = phase === "feedback" ? correct ? "is-correct" : selected === choice ? "is-wrong" : "" : ""; return <button onClick={() => answer(choice)} disabled={phase !== "playing"} className={state} key={`${question.id}-${choice}`}><i>{choiceIndex + 1}</i><b>{choice}</b>{phase === "feedback" && correct ? <Check size={21} /> : null}</button>; })}</div>{phase === "feedback" ? <div className={`am-feedback ${canonical(selected ?? "") === canonical(question.correctChoice) ? "is-correct" : "is-wrong"}`} role="status"><i>{canonical(selected ?? "") === canonical(question.correctChoice) ? "✦" : "↗"}</i><div><b>{canonical(selected ?? "") === canonical(question.correctChoice) ? "Multiplier spark!" : "Keep building!"}</b><p>{feedback}</p></div><button onClick={advance}>{hearts <= 0 || index >= questions.length - 1 ? "RESULTS" : "NEXT"}<ChevronRight size={17} /></button></div> : null}</section></main>;
}
