import { useState } from "react";
import { ArrowLeft, ChevronRight, LockKeyhole, Music2, Play, Sparkles, Star, VolumeX } from "lucide-react";
import MultiplicationMissionWorld from "@/components/MultiplicationMissionWorld";
import { MULTIPLICATION_MISSION_ROUTES } from "@/game/multiplicationMissionCurriculum";
import { isMultiplicationMasterUnlocked, readMultiplicationMissionProgress } from "@/game/multiplicationMissionProgress";
import type { MultiplicationMissionProgressState, MultiplicationRouteId } from "@/game/multiplicationMissionTypes";
import "./areaMission.css";

export default function MultiplicationMissionChapter({ onExit, musicOn, onToggleMusic }: { onExit: () => void; musicOn: boolean; onToggleMusic: () => void }) {
  const [activeRoute, setActiveRoute] = useState<MultiplicationRouteId | null>(() => { if (typeof window === "undefined") return null; const requested = new URLSearchParams(window.location.search).get("multiply-route") as MultiplicationRouteId | null; return requested && MULTIPLICATION_MISSION_ROUTES.some((route) => route.id === requested) ? requested : null; });
  const [progress, setProgress] = useState<MultiplicationMissionProgressState>(readMultiplicationMissionProgress); const lessons = MULTIPLICATION_MISSION_ROUTES.filter((route) => !route.isMaster); const unlocked = isMultiplicationMasterUnlocked(progress);
  if (activeRoute) return <MultiplicationMissionWorld routeId={activeRoute} musicOn={musicOn} onToggleMusic={onToggleMusic} onBack={() => { setProgress(readMultiplicationMissionProgress()); setActiveRoute(null); }} />;
  return <main className="am-chapter mm-chapter" aria-labelledby="multiplication-mission-title"><div className="am-map-orb am-map-orb-a" /><div className="am-map-orb am-map-orb-b" /><header className="am-topbar"><button onClick={onExit}><ArrowLeft size={17} /> MAIN MENU</button><strong><i>×</i> MULTIPLY & CONQUER <b>MOSY MATH ADVENTURE · UNIT 5</b></strong><button onClick={onToggleMusic}>{musicOn ? <Music2 size={18} /> : <VolumeX size={18} />} {musicOn ? "MUSIC" : "MUTED"}</button></header><section className="am-hero"><div className="am-hero-visual mm-hero-visual"><i /><b>×</b><em>=</em></div><div><p><Sparkles size={15} /> UNIT 5 MULTIPLICATION ARENA</p><h1 id="multiplication-mission-title">Multiply<br /><span>& Conquer</span></h1><h2>Build comparisons, forge equations, unlock properties, and launch multiplication patterns.</h2><div><b>7 <small>LESSON MISSIONS</small></b><b>{lessons.reduce((total, route) => total + progress[route.id as keyof MultiplicationMissionProgressState].completedLevels.length, 0)} <small>POWER GEMS</small></b><b>1 <small>MASTER EXAM</small></b></div></div></section><section className="am-route-section"><header><div><p>POWER UP IN ORDER</p><h2>Choose a multiplication mission</h2></div><span>Easy → Normal → Hard</span></header><div className="am-route-grid">{lessons.map((route) => { const item = progress[route.id as keyof MultiplicationMissionProgressState]; return <article key={route.id} style={{ "--am-accent": route.accent, "--am-soft": route.accentSoft } as React.CSSProperties}><div><span>{route.lesson}</span><i>{route.icon}</i></div><div className="am-route-icon"><i>{route.icon}</i><b>✦</b></div><p>{route.subtitle}</p><h3>{route.shortTitle}</h3><small>{route.description}</small><em><b>✦</b> {item.completedLevels.length} / 3 POWER GEMS</em><button onClick={() => setActiveRoute(route.id)}><Play size={15} fill="currentColor" /> PLAY {route.shortTitle.toUpperCase()}<ChevronRight size={16} /></button></article>; })}</div></section><section className={`am-final ${unlocked ? "is-open" : "is-locked"}`}><div className="am-final-orb">★</div><div><p>{unlocked ? "MASTER UNIT EXAM UNLOCKED" : "MASTER UNIT EXAM · LOCKED"}</p><h2>Multiplication Master Exam</h2><span>Mix every Unit 5 skill using the teacher-supplied Unit Five Assessment.</span><b>{lessons.filter((route) => progress[route.id as keyof MultiplicationMissionProgressState].completedLevels.includes("hard")).length} / 7 ROUTES MASTERED</b></div><button disabled={!unlocked} onClick={() => setActiveRoute("multiplication-master-exam")}>{unlocked ? <><Star size={17} fill="currentColor" /> START MASTER EXAM</> : <><LockKeyhole size={16} /> MASTER THE 7 ROUTES</>}</button></section></main>;
}
